package foo.excep.handle;

import java.io.IOException;

public class MultipleException extends IOException {
	
	//When I extended an Exception in RunTimeException it was not mandatory to put try/catch block or put throws word in function declaration
	// public class MultipleException extends ArithmeticException {	

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
}//end MultipleException
